ads/urls.py
from django.urls import path
from . import views

app_name ="ads"
urlpatterns=[
    path('ad/<int:pk>',views.DetailAdView.as_view(),name='ad_detail'),
    path('ad/<int:pk>/image',views.file_stream,name='ad_image'),
    path('ad/create',views.CreateAdView.as_view(),name='ad_create'),
    path('ad/<int:pk>/update',views.UpdateAdView.as_view(),name='ad_update'),
    path('ad/<int:pk>/delete',views.DeleteAdView.as_view(),name='ad_delete'),
    path('ads/',views.ListAdView.as_view(),name='ad_list'),
    path('ad/<int:pk>/favorite',views.favorite,name='favorite'),
    path('ad/<int:pk>/unfavorite',views.unfavorite,name='unfavorite'),
    path('',views.ListAdView.as_view(),),
    path('ad_picture/<int:pk>',views.file_stream,name='ad_image'),
    path('ad/<int:pk>/comment',views.CreateComment,name='ad_comment'),
    path('comment/<int:pk>/delete',views.DeleteComment.as_view(),name='delete_comment'),
    ]

finalcourse/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from ads import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),



    #### site apps 
    path('',include('ads.urls')),
    path('json/',include('jsonapp.urls')),
    path('favs/',include('favs.urls')),

    ### site logs
    ###### local sign
    path('accounts/login/',LoginView.as_view(template_name='ads/login.html')),
    path('accounts/logout/',LogoutView.as_view(),name='logout'),
    ########### oauth login 2 apps 
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('social_django.urls',namespace='social')),
    




]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ads/models.py
from django.db import models
from django.shortcuts import redirect
from django.urls.base import reverse
from django.utils.translation import TranslatorCommentWarning
from django.conf import settings
from taggit.managers import TaggableManager
# Create your models here.
class Ad(models.Model):
    title=models.CharField(max_length=150,)
    price=models.FloatField()
    text=models.TextField()
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='adFav', related_name='favorite_ads',blank=True)
    tags=TaggableManager()
    ###### pics
    image=models.BinaryField(null=True,blank=True,editable=True)
    content_type=models.CharField(max_length=500,null=True,blank=True,help_text='the MIMEType of the file')

    ########
    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    Updated_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    def get_absolute_url (self):
        return reverse('ads:ad_detail',kwargs={'pk':self.pk})
class adFav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.ad.title[:10])
class comment(models.Model):
    Author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True,blank=True)
    text=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    Updated_at=models.DateTimeField(auto_now=True)
    post=models.ForeignKey(to='Ad',on_delete=models.CASCADE,related_name='comments',null=True,blank=True)
    def __str__(self):
        return self.text
    def get_absolute_url(self):
        print(self.post.pk)
        return reverse('ads:ad_detail',kwargs={'pk':self.post.pk})

ads/forms.py
from django import forms
from django.forms import fields

from ads import models

from django.core.files.uploadedfile import InMemoryUploadedFile

class CreateAdForm(forms.ModelForm):
    max_upload_limit=5*1024*1024
    max_limit_text='5M'
    image=forms.FileField(required=False,label='File to upload <= '+max_limit_text) 
    upload_field_name='image'
    class Meta:
        model=models.Ad
        fields=['title','price','text','tags','image']
    
    def clean(self):
        cleaned_data=super().clean()
        img=cleaned_data.get('image')
        if img is None:   return 
        if len(img)> self.max_upload_limit:
            self.add_error('image','file must be <='+ self.max_limit_text)
    

    def save(self,commit=True):
        instance=super(CreateAdForm,self).save(commit=False)
        file=instance.image
        if isinstance(file,InMemoryUploadedFile):
            bytearr=file.read();
            instance.content_type= file.content_type
            instance.image=bytearr
        if commit:
            instance.save()
            self.save_m2m()
        return instance

ads/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render,redirect
from ads import models,forms 
from django.views.generic import CreateView,UpdateView,DeleteView,ListView,DetailView,View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
class CreateAdView(View,LoginRequiredMixin):
    model=models.Ad
    template_name='ads/CreateAd.html'
    def get(self,request,pk=None):

        form=forms.CreateAdForm()
        context={'form':form}
        return render(request,self.template_name,context)

    def post(self,request,pk=None):
        form=forms.CreateAdForm(request.POST,request.FILES or None)
        if not form.is_valid():
            context={'form':form}
            return render(request,self.template_name,context)
        ad=form.save(commit=False)
        ad.author=request.user
        ad.save()
        form.save_m2m()
        return redirect(self.success_url)
    success_url='/ads'

# Create your views here.
class UpdateAdView(View,LoginRequiredMixin):
    model=models.Ad
    template_name='ads/CreateAd.html'
    success_url='/ads'

    def get(self,request,pk):
        ad=get_object_or_404(models.Ad,id=pk,author=self.request.user)
        form=forms.CreateAdForm(instance=ad)
        context={'form':form,'update':True}
        return render(request,self.template_name,context)

    def post(self,request,pk=None):
        ad=get_object_or_404(models.Ad,id=pk)
        form=forms.CreateAdForm(request.POST,request.FILES or None,instance=ad)
        if not form.is_valid():
            context={'form':form,'update':True}
            return render(request,self.template_name,context)
        ad=form.save(commit=False)
        ad.save()
        form.save_m2m()
        return redirect(self.success_url)
class DeleteAdView(DeleteView,LoginRequiredMixin):
    model=models.Ad
    template_name='ads/DeleteAd.html'
    success_url='/ads'
class DetailAdView(DetailView):
    model=models.Ad
    template_name='ads/DetailAd.html'
class ListAdView(ListView):
    def get(self,request):
        if request.GET.get('search'):
            search=request.GET.get('search')
            query=Q(title__contains=search)
            query.add(Q(text__contains=search),Q.OR)
            query.add(Q(tags__name=search),Q.OR)
            print(models.Ad.objects.filter(tags__name='fashion'))   
            ads=models.Ad.objects.filter(query).select_related().order_by('-created_at')

            ads=list(set(ads))[:10]

        else:   
            ads=models.Ad.objects.all()
        favorite_list=[]
        if request.user.is_authenticated :
            favorite_list=self.request.user.favorite_ads.values('id')
            favorite_list=[fav['id'] for fav in favorite_list]
        data={"ad_list":ads,'favorite_list':favorite_list}
        return render(request,'ads/ListAd.html',data)
def file_stream(request,pk):
    ad=get_object_or_404(models.Ad,id=pk)
    print(ad.content_type)
    response=HttpResponse()
    response['content-type']=ad.content_type
    response['content-length']=len(ad.image)
    response.write(ad.image)
    return response

@login_required
def CreateComment(request,pk):
    model=get_object_or_404(models.Ad,id=pk)
    if  request.method == 'POST':
        comment=models.comment(text=request.POST['comment'])
        comment.Author=request.user
        comment.post=model
        comment.save()
    return redirect('/ad/{}'.format(pk))
class DeleteComment(LoginRequiredMixin,DeleteView):
    model=models.comment
    template_name='ads/DeleteComment.html'
    def get_success_url(self):
        return reverse('ads:ad_detail',kwargs={'pk':self.get_context_data()['comment'].post.id})
    def get_context_data(self, **kwargs):
        data=super().get_context_data(**kwargs)
        self.success_url=reverse('ads:ad_detail',kwargs={'pk':data['comment'].post.id})
        print(self.success_url)
        return data
@login_required
@method_decorator(csrf_exempt,name='dispatch')
def favorite(request,pk):
    ad=get_object_or_404(models.Ad,pk=pk)
    fav=models.adFav(user=request.user,ad=ad)
    fav.save()
    return HttpResponse()
@login_required
@method_decorator(csrf_exempt,name='dispatch')
def unfavorite(request,pk):
    ad=get_object_or_404(models.Ad,pk=pk)
    fav=models.adFav.objects.get(user=request.user.id,ad=ad)
    fav.delete()
    return HttpResponse()

templates/ads/CreateAd.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block body %}

<div class='container'>
<form method='post' id='upload_form' enctype="multipart/form-data">
{% csrf_token %}

{% bootstrap_form form  %}
<input type="submit" class='btn btn-primary ' value="Submit"/>

<a href="/ads" class="btn btn-secondary">Cancel</a>
</form>
<script>

$("#upload_form").submit(function(){
  console.log('checking file size ...');
  if (window.File && window.FileReader && window.FileList && window.Blob){
    var file=$( '#id_image')[0].files[0];
    if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < 5.0MB" );
      return false;
    }
  }
});
  </script>

 
</div>
{% endblock %}

templates/ads/DeleteAd.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load humanize %} 
{% block body %}
<div class="container">
    
    <h1>Delete Ad</h1>
    
    <p>Are you sure you want to delete the ad: {{ad}}?</p>
    
    <form action="" method="POST">
{% csrf_token %}     
 <input type="submit" class="btn btn-primary" value="Yes, delete.">
      <a href="{% url 'ads:ad_list' %}" class="btn btn-secondary">Cancel</a>
    
    </form>
    
    </div>
    {% endblock %}

templates/ads/DeleteComment.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load humanize %} 
{% block body %}
<div class="container">
    
    <h1>Delete Ad</h1>
    
    <p>Are you sure you want to delete the comment: {{comment}}?</p>
    
    <form action="" method="POST">
{% csrf_token %}     
 <input type="submit" class="btn btn-primary" value="Yes, delete.">
      <a href="{% url 'ads:ad_detail' comment.post.id %}" class="btn btn-secondary">Cancel</a>
    
    </form>
    
    </div>
    {% endblock %}

templates/ads/DetailAd.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load humanize %} 
{% block body %}
<div class="container">
    

    <div id="overlay" class="overlay" style="text-align: center;"
       onclick="document.getElementById('overlay').style.display = 'none';" >
    <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_image' ad.id %}">
    </div>
    
    <span style="float: right;">
        ({{ ad.created_at|naturaltime }})
        {% if user == ad.author %}
        <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
        <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>

        {% endif %}
    </span>
    <h1>{{ad}}</h1>
    
    <img style="float:right; max-width:30%;" src="{% url 'ads:ad_image' ad.id %}"
        onclick="document.getElementById('overlay').style.display = 'block';">
    
    <p>
{{ad.text}}

    </p>
<p>Tags: {%  for tag in ad.tags.all %} <span style='background-color: blueviolet; padding:4px; border-radius: 5px; color:whitesmoke'>{{tag}}</span> {% endfor %}</p>
    <p>
    Price: ${{ad.price}}
    </p>
    
    <br clear="all"/>
    <p>
    <form method="post" action="{% url 'ads:ad_comment' ad.id %}">
        {% csrf_token %}        
    
    <div id="div_id_comment" class="form-group"> <label for="id_comment" class="control-label ">
                    Comment
    </label> <div class="controls ">
    <input type="text" name="comment" maxlength="500" minlength="3" class="textinput textInput form-control" id="id_comment"> </div> </div>
    
    <input type="submit" value="Submit">
    <input type="submit" value="All Ads" onclick='window.location.href="{% url 'ads:ad_list' %}";return false;'>
    </form>
    </p>
    
    
    {% for comment in ad.comments.all reversed %}

    <p>
        {{comment}}  ({{ comment.created_at|naturaltime }})

        {% if user == comment.Author %} 
        <a href="{% url 'ads:delete_comment' comment.id %}"><i class="fa fa-trash"></i></a>

        {% endif %}

    </p>
    {% endfor %}
    
    
    </div>
    {% endblock %}

templates/ads/ListAd.html
{% extends 'home.html' %}
{% load static %}
{% block body %}

<script >function favpost(url,id){
    fetch(url,{
        method:"POST",
        mode:'cors',
        cache:'no-cache',
        credentials:"same-origin",
        headers:{
            'content_type':'application/x-www-form-urlencoded',
    
        },
        redirect:'follow',
        referrer:'no-referrer',
    }).then(function(data){
        console.log(url,'finished');
        $('#unfavorite_star_'+id).toggle();
        $('#favorite_star_'+id).toggle();
    }).catch(()=>{
        console.log(url,'error');
    })
        
    }</script>

<div class="container">
    
    <h1 style="font-weight: 500;"><strong>Ads </strong> </h1>
    <div  style='right:100px;  position: absolute;'> 

        <form action="" method="GET"  >
                <input type="text" name='search'   placeholder="search Ad">


            <button type='submit' = >
    
            <i class='fa fa-search'></i>
            </button>
            <a href="."> <i class="fas fa-redo-alt"></i></a>
        </form>
    </div>
    <p>
    
    <ul>
        {% for ad in ad_list %} 

        <li style="color:darkslategrey; font-size: larger; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; font-style: italic;">
            <a href="{% url 'ads:ad_detail' ad.id %}">     {{ad}}            </a>
            
      {% if user.is_authenticated %} 

            {% if user == ad.author %}
            (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
            <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
            {% endif %}
        {% endif %}
        <a href='#' onclick=favpost('{% url 'ads:unfavorite' ad.id %}',{{ad.id}}) id='unfavorite_star_{{ad.id}}'  {% if ad.id  not in favorite_list %} style='display:none; ' {% endif %}>
              <span class='fa-stack' style='width: 5px;'> 
                <i class="fa fa-star fa-stack-1x" style='color:orange;' ></i>
                <i class="fa fa-star-o fa-stack-1x" ></i> </span>    
        </a>
        <a href='#' onclick=favpost('{% url 'ads:favorite' ad.id %}',{{ad.id}})
         id='favorite_star_{{ad.id}}'  {% if ad.id  in favorite_list %} style='display:none; ' {% endif %}>
         <span class='fa-stack' style='width: 5px;'> 
            <i class="fa fa-star-o fa-stack-1x" ></i> </span>  
               </a>
        
        
        {% endfor %}
    </li>

    </ul>
    
    </p>
 <div >
    <p>
    <strong> <a href="{% url 'ads:ad_create' %}"> create new AD  </a></strong>|  
     {% if user.is_authenticated %}   
       <a href="{% url 'logout' %}">Logout  </a>         
       {% else %}
       <a href="{% url 'logout' %}">Login</a>
       {% endif %}

    </p>
 </div>
    
    </div>


{% endblock %}

templates/ads/commentform.html
<form method="post" action="{% url 'ads:ad_comment' ad.id %}">
    {% csrf_token %}        

<div id="div_id_comment" class="form-group"> <label for="id_comment" class="control-label ">
                Comment
</label> <div class="controls ">
<input type="text" name="comment" maxlength="500" minlength="3" class="textinput textInput form-control" id="id_comment"> </div> </div>

<input type="submit" value="Submit">
<input type="submit" value="All Ads" onclick='window.location.href="{% url 'ads:ad_list' %}";return false;'>
</form>

templates/ads/login.html
{% extends 'home.html' %}
{% block body %}




<div class="container">
    




  
<p class='alert alert-danger'style='font-size:25px; text-align: center; margin-top: 2px; margin-bottom: 2px;'><strong>Please login to see this site.</strong></p>
  


<div style='margin-top:35px; '>

<form method="post" action="/accounts/login/" >
{% csrf_token %}

<div id="div_id_username" class="form-group"> <label for="id_username" class="control-label  requiredField">
                Username<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="textinput textInput form-control" required id="id_username"> </div> </div> <div id="div_id_password" class="form-group"> <label for="id_password" class="control-label  requiredField">
                Password<span class="asteriskField">*</span> </label> <div class="controls "> <input type="password" name="password" autocomplete="current-password" class="textinput textInput form-control" required id="id_password"> </div> </div>

<input type="submit" class="btn btn-primary" value="Login Locally" />

</form>
<hr style=' margin-bottom: 2px'/>
<P style='font-size:15px; text-align: center; margin-top: 2px; margin-bottom: 2px;'><strong>OR</strong></P>

<hr style='  margin-top: 2px;'/>
<a id="github-button" class="btn  btn-primary btn-social btn-github" href="{% url 'social:begin' 'github' %}">
    <i class="fa fa-github"></i> Sign in with GitHub
</a>
</div>
</div>
{% endblock %}