ads/urls.py
from django.urls import path
from . import views

app_name ="ads"
urlpatterns=[
    path('ad/<int:pk>',views.DetailAdView.as_view(),name='ad_detail'),
    path('ad/<int:pk>/image',views.file_stream,name='ad_image'),
    path('ad/create',views.CreateAdView.as_view(),name='ad_create'),
    path('ad/<int:pk>/update',views.UpdateAdView.as_view(),name='ad_update'),
    path('ad/<int:pk>/delete',views.DeleteAdView.as_view(),name='ad_delete'),
    path('ads/',views.ListAdView.as_view(),name='ad_list'),
    path('ad/<int:pk>/favorite',views.favorite,name='favorite'),
    path('ad/<int:pk>/unfavorite',views.unfavorite,name='unfavorite'),
    path('',views.ListAdView.as_view(),),
    path('ad_picture/<int:pk>',views.file_stream,name='ad_image'),
    path('ad/<int:pk>/comment',views.CreateComment,name='ad_comment'),
    path('comment/<int:pk>/delete',views.DeleteComment.as_view(),name='delete_comment'),
    ]

favs/urls.py
from django.urls import path 
from favs import views


app_name='favs'
urlpatterns=[
    path('fav/<int:pk>',views.DetailThingView.as_view(),name='thing_detail'),
    path('fav/create',views.CreateThingView.as_view(),name='thing_create'),
    path('fav/<int:pk>/update',views.UpdateThingView.as_view(),name='thing_update'),
    path('fav/<int:pk>/delete',views.DeleteThingView.as_view(),name='thing_delete'),
    path('',views.ListThingView.as_view(),name='thing_list'),
    path('fav/<int:pk>/favorite',views.favorite,name='favorite'),
    path('fav/<int:pk>/unfavorite',views.unfavorite,name='unfavorite'),
]

finalcourse/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from ads import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),



    #### site apps 
    path('',include('ads.urls')),
    path('json/',include('jsonapp.urls')),
    path('favs/',include('favs.urls')),

    ### site logs
    ###### local sign
    path('accounts/login/',LoginView.as_view(template_name='ads/login.html')),
    path('accounts/logout/',LogoutView.as_view(),name='logout'),
    ########### oauth login 2 apps 
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('social_django.urls',namespace='social')),
    




]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

favs/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.shortcuts import redirect
from django.urls import reverse 
# Create your models here.
class thing(models.Model):
    title=models.CharField(max_length=500,validators=[MinLengthValidator(2,'please enter some greater title minimun length is 2 characters 😉')])
    text = models.TextField()
    owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    favorites=models.ManyToManyField(settings.AUTH_USER_MODEL,through='fav',related_name='favorite_things')
    created_at=models.DateTimeField(auto_now_add=True,)
    Updated_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('favs:thing_detail', kwargs={'pk':self.id})
class fav(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    thing=models.ForeignKey('thing',on_delete=models.CASCADE)


    class Meta:
        unique_together=['thing','user']

    def __str__(self) :
        return self.user.username+' likes ❤ '+self.thing.title[:10]

favs/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse
from django.views.generic import CreateView,UpdateView,DeleteView,DetailView,ListView,View
from django.contrib.auth.mixins import LoginRequiredMixin
from favs import models 
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

class CreateThingView(CreateView,LoginRequiredMixin):
    model=models.thing
    template_name='favs/CreateThing.html'
    fields=['title','text']
    def form_valid(self, form):
        thing=form.save(commit = False)
        thing.owner=self.request.user
        thing.save()        
        return super().form_valid(form)

class UpdateThingView(UpdateView,LoginRequiredMixin):
    model=models.thing
    template_name='favs/CreateThing.html'
    fields=['title','text']
    def get_queryset(self) :
        return super().get_queryset().filter(owner=self.request.user)
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['update']=True
        return data
    

    
class DeleteThingView(DeleteView,LoginRequiredMixin):
    model=models.thing
    template_name='favs/DeleteThing.html'
    def get_queryset(self) :
        return super().get_queryset().filter(owner=self.request.user)
    success_url='/favs'
class DetailThingView(DetailView,LoginRequiredMixin):
    model=models.thing
    template_name='favs/DetailThing.html'
class ListThingView(ListView):
    def get(self,request):
        things=models.thing.objects.all()
        favorite_list=[]
        if request.user.is_authenticated :
            favorite_list=self.request.user.favorite_things.values('id')
            favorite_list=[fav['id'] for fav in favorite_list]
        data={"thing_list":things,'favorite_list':favorite_list}
        return render(request,'favs/ListThing.html',data)
@login_required
@method_decorator(csrf_exempt,name='dispatch')
def favorite(request,pk):
    thing=get_object_or_404(models.thing,pk=pk)
    fav=models.fav(user=request.user,thing=thing)
    fav.save()
    return HttpResponse()
@login_required
@method_decorator(csrf_exempt,name='dispatch')
def unfavorite(request,pk):
    thing=get_object_or_404(models.thing,pk=pk)
    fav=models.fav.objects.get(user=request.user.id,thing=thing)
    fav.delete()
    return HttpResponse()

templates/favs/CreateThing.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block body %}

<div class='container'>
<form method='post' id='upload_form' >
{% csrf_token %}

{% bootstrap_form form  %}
<input type="submit" class='btn btn-primary ' value="Submit"/>

<a href="/favs" class="btn btn-secondary">Cancel</a>
</form>


 
</div>
{% endblock %}

templates/favs/DeleteThing.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load humanize %} 
{% block body %}
<div class="container">
    
    <h1>Delete Ad</h1>
    
    <p>Are you sure you want to delete the thing: {{thing}}?</p>
    
    <form action="" method="POST">
{% csrf_token %}     
 <input type="submit" class="btn btn-primary" value="Yes, delete.">
      <a href="{% url 'favs:thing_list' %}" class="btn btn-secondary">Cancel</a>
    
    </form>
    
    </div>
    {% endblock %}

templates/favs/DetailThing.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load humanize %} 
{% block body %}
<div class="container">
    


    
    <span style="float: right;">
        ({{ thing.created_at|naturaltime }})
        {% if user == thing.owner %}
        <a href="{% url 'favs:thing_update' thing.id %}"><i class="fa fa-pencil"></i></a>
        <a href="{% url 'favs:thing_delete' thing.id %}"><i class="fa fa-trash"></i></a>

        {% endif %}
    </span>
    <h1>{{thing}}</h1>

    
    <p>
{{thing.text}}
    </p>

    
    <br clear="all"/>
<p> <strong> <a href="{% url 'favs:thing_list' %}"> back to all things </a></strong></p>
    
    
    </div>
    {% endblock %}

templates/favs/ListThing.html
{% extends 'home.html' %}

{% load static %}

{% block head %}  
<script >function favpost(url,thing_id){
    fetch(url,{
        method:"POST",
        mode:'cors',
        cache:'no-cache',
        credentials:"same-origin",
        headers:{
            'content_type':'application/x-www-form-urlencoded',
    
        },
        redirect:'follow',
        referrer:'no-referrer',
    }).then(function(data){
        console.log('url','finished');
        $('#unfavorite_star_'+thing_id).toggle();
        $('#favorite_star_'+thing_id).toggle();
    }).catch(()=>{
        console.log(url,'error')
    })
        
    }</script>
{% endblock %}
{% block body %}



<div class="container">
    
    <h1 style="font-weight: 500;"><strong>Favorite Things </strong> </h1>
    <p>
    
    <ul>
        {% for thing in thing_list %} 

        <li style="color:darkslategrey; font-size: larger; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; font-style: italic;">
            <a href="{% url 'favs:thing_detail' thing.id %}">     {{thing}}            </a>
            
      {% if user.is_authenticated %} 

            {% if user == thing.owner %}
            (<a href="{% url 'favs:thing_update' thing.id %}">Edit</a> |
            <a href="{% url 'favs:thing_delete' thing.id %}">Delete</a>)
            {% endif %}
        {% endif %}
        <a href='#' onclick=favpost("{% url 'favs:unfavorite' thing.id %}",{{thing.id}}) id='unfavorite_star_{{thing.id}}'  {% if thing.id  not in favorite_list %} style='display:none; ' {% endif %}>
              <span class='fa-stack' style='width: 5px;'> 
                <i class="fa fa-star fa-stack-1x" style='color:orange;' ></i>
                <i class="fa fa-star-o fa-stack-1x" ></i> </span>    
        </a>
        <a href='#' onclick=favpost("{% url 'favs:favorite' thing.id %}",{{thing.id}})
         id='favorite_star_{{thing.id}}'  {% if thing.id  in favorite_list %} style='display:none; ' {% endif %}>
         <span class='fa-stack' style='width: 5px;'> 
            <i class="fa fa-star-o fa-stack-1x" ></i> </span>  
               </a>
        
        
        {% endfor %}
    </li>

    </ul>
    
    </p>
 <div >
    <p>
    <strong> <a href="{% url 'favs:thing_create' %}">Add new thing  </a></strong>| <a href="{% url 'logout' %}">Logout  </a>
    </p>
 </div>
    
    </div>


{% endblock %}